name: Build

on:
  workflow_dispatch:
  push:
    branches:
      - tt-*
  pull_request:
    branches:
      - tt-*

jobs:
  build:
    uses: ./.github/workflows/build-reusable.yaml
    with:
      artifact-name: build
